# Generated by Django 4.2.1 on 2023-06-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='contributer',
            new_name='contributor',
        ),
        migrations.AlterField(
            model_name='food',
            name='url',
            field=models.TextField(),
        ),
    ]
