# Generated by Django 4.2.1 on 2023-06-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_rename_contributer_food_contributor_alter_food_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
