# Generated by Django 4.2.1 on 2023-06-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.TextField(),
        ),
    ]
